services:
  web:
    image: rom2555/drf-api-server:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Переменные берутся из .env файла
    command: gunicorn --bind 0.0.0.0:8000 --reload DRF_API_SERVER.wsgi:application
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    restart: unless-stopped
